Add ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -200,62 +200,102 @@ jobs:
           IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/streamlit-snowflake:latest
           docker push $IMAGE_NAME
 
-      # 5. Install Snowflake Python dependencies
-      - name: Install Snowflake Python Connector
-        run: |
-          pip install snowflake-connector-python snowflake-snowpark-python
+      # # 5. Install Snowflake Python dependencies
+      # - name: Install Snowflake Python Connector
+      #   run: |
+      #     pip install snowflake-connector-python snowflake-snowpark-python
 
-      # 6. Deploy/alter Snowflake service
-      - name: Deploy Snowflake Service
+      # # 6. Deploy/alter Snowflake service
+      # - name: Deploy Snowflake Service
+      #   env:
+      #     SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
+      #     SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
+      #     SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
+      #     SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
+      #     SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
+      #     SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
+      #     SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
+      #     IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/streamlit-snowflake:latest
+      #   run: |
+      #     python - <<'EOF'
+      #     import snowflake.connector
+      #     import os
+
+      #     conn = snowflake.connector.connect(
+      #         account=os.getenv("SNOWFLAKE_ACCOUNT"),
+      #         user=os.getenv("SNOWFLAKE_USER"),
+      #         password=os.getenv("SNOWFLAKE_PASSWORD"),
+      #         role=os.getenv("SNOWFLAKE_ROLE"),
+      #         warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
+      #         database=os.getenv("SNOWFLAKE_DATABASE"),
+      #         schema=os.getenv("SNOWFLAKE_SCHEMA")
+      #     )
+      #     cs = conn.cursor()
+
+      #     service_name = "STREAMLIT_APP"
+      #     image_url = os.getenv("IMAGE_NAME")
+
+      #     try:
+      #         cs.execute(f"ALTER SERVICE {service_name} FROM SPECIFICATION $$ containers: - name: streamlit image: {image_url} args: ['streamlit','run','streamlit.py','--server.port','8501','--server.address','0.0.0.0'] endpoints: - name: httpendpoint port: 8501 public: true $$;")
+      #         print("Service altered successfully.")
+      #     except Exception as e:
+      #         print("ALTER failed:", e)
+      #         cs.execute(f"""
+      #             CREATE SERVICE {service_name}
+      #             IN COMPUTE POOL my_compute_pool
+      #             FROM SPECIFICATION $$
+      #             containers:
+      #               - name: streamlit
+      #                 image: {image_url}
+      #                 args: ["streamlit", "run", "streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
+      #             endpoints:
+      #               - name: httpendpoint
+      #                 port: 8501
+      #                 public: true
+      #             $$;
+      #         """)
+      #         print("Service created successfully.")
+
+      #     cs.close()
+      #     conn.close()
+      #     EOF
+
+
+          
+      - name: Setup Snowflake CLI
+        uses: snowflakedb/snowflake-cli-action@v1.5
+        with:
+          cli-version: "latest"
+          default-config-file-path: "config.toml"
+
+      - name: Check if Snowflake is reachable
+        run: |
+          curl -I https://kcb69289.us-west-2.snowflakecomputing.com || true
+
+      - name: Test Snowflake Connection
         env:
-          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
-          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
-          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
-          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
-          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
-          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
-          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
-          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/streamlit-snowflake:latest
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: VAIDEHI
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: kcb69289
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: Kasmodigital@123
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: ACCOUNTADMIN
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: COMPUTE_WH
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: DASH_DB
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: DASH_SCHEMA
         run: |
-          python - <<'EOF'
-          import snowflake.connector
-          import os
+          snow --version
+          snow connection test --debug
 
-          conn = snowflake.connector.connect(
-              account=os.getenv("SNOWFLAKE_ACCOUNT"),
-              user=os.getenv("SNOWFLAKE_USER"),
-              password=os.getenv("SNOWFLAKE_PASSWORD"),
-              role=os.getenv("SNOWFLAKE_ROLE"),
-              warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
-              database=os.getenv("SNOWFLAKE_DATABASE"),
-              schema=os.getenv("SNOWFLAKE_SCHEMA")
-          )
-          cs = conn.cursor()
-
-          service_name = "STREAMLIT_APP"
-          image_url = os.getenv("IMAGE_NAME")
-
-          try:
-              cs.execute(f"ALTER SERVICE {service_name} FROM SPECIFICATION $$ containers: - name: streamlit image: {image_url} args: ['streamlit','run','streamlit.py','--server.port','8501','--server.address','0.0.0.0'] endpoints: - name: httpendpoint port: 8501 public: true $$;")
-              print("Service altered successfully.")
-          except Exception as e:
-              print("ALTER failed:", e)
-              cs.execute(f"""
-                  CREATE SERVICE {service_name}
-                  IN COMPUTE POOL my_compute_pool
-                  FROM SPECIFICATION $$
-                  containers:
-                    - name: streamlit
-                      image: {image_url}
-                      args: ["streamlit", "run", "streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
-                  endpoints:
-                    - name: httpendpoint
-                      port: 8501
-                      public: true
-                  $$;
-              """)
-              print("Service created successfully.")
-
-          cs.close()
-          conn.close()
-          EOF
+      - name: Deploy to Snowflake
+        env:
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: VAIDEHI
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: kcb69289
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: Kasmodigital@123
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: ACCOUNTADMIN
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: COMPUTE_WH
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: DASH_DB
+          SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: DASH_SCHEMA
+        run: |
+          # snow sql -q "USE ROLE ACCOUNTADMIN; USE WAREHOUSE COMPUTE_WH;"
+          # snow sql -q "PUT file://snowflake/COP_FINANCE/update.yaml @FINANCE.REPORT.SPECS OVERWRITE = TRUE;"
+          # snow sql -q "ALTER SERVICE CI_CD_SERVICE FROM @FINANCE.REPORT.SPECS SPECIFICATION_FILE = 'update.yaml';"
+          # snow sql -q "ALTER SERVICE CI_CD_SERVICE RESUME;"
